export const UpdateTaskActionTypes = {
    UPDATE_TASK: 'UPDATE_TASK',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',
    DELETE_TASK: 'DELETE_TASK',
}
